// usertype action
export const SET_USER = 'SET_USER'

//PLAYLIST ACTION
export const SET_PLAYLISTS = 'SET_PLAYLISTS';
export const SET_CURRENT_PLAYLIST = 'SET_CURRENT_PLAYLIST';
export const SET_CURRENT_SONG_INDEX = 'SET_CURRENT_SONG_INDEX';
export const SET_CURRENTLY_PLAYING_PLAYLIST = 'SET_CURRENTLY_PLAYING_PLAYLIST';
export const SET_IS_SONG_PLAYING ='SET_IS_SONG_PLAYING'
//Access Token action
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';